const tran=[

["English","Tree Name:","Given Names:","Family Name:","Gender:","Birth:","Death:","Other Info:","Relation:","Buttons:","Male","Female","Both","None","Choose","Married > ","Parental > ","Siblings > ","Adopted > ","Divorced > ","Unwed > ","Background Colour","Select Multiple","Translate:","ID Lines: select id pair and set relation on left.","Black","White","Red","Green","Blue","Orange","Yellow","Grey","The relation between ", " and ",". You can change this by using the relation drop down on the left.","New Person","Update Selected","Delete Selected","Fullscreen","Normal","New Tree","Save Tree","Load Tree","Center Tree","Hide","Show","undecided","If you want to clear this tree type:","Can't add person without relation, select someone first!","Can't delete person with sub branches or id:0","Enter a tree name first"],

["Francais","Nom de l'arbre :","Prénoms :","Nom de famille :","Sexe :","Naissance :","Décès :","Autres informations :","Relation :","Boutons :", "Homme", "Femme", "Les deux", "Aucun", "Choisir", "Marié > "," Parental > "," Frères et sœurs > "," Adoptés > "," Divorcés > "," Célibataires > ", "Couleur d'arrière-plan", "Sélectionner plusieurs", "Traduire :", "Lignes d'identification : sélectionner la paire d'identifiants et définir la relation à gauche.", "Noir", "Blanc", "Rouge", "Vert", "Bleu", "Orange", "Jaune", "Gris", "La relation entre ", " et ", ". Vous pouvez modifier cela en utilisant la liste déroulante de relations sur la gauche. ", " Nouvelle personne ", " Mettre à jour la sélection ", "Supprimer la sélection", "Plein écran", "Normale", "Nouvel arbre", "Enregistrer l'arbre", "Charger l'arbre", "Centrer l'arbre", "Masquer", "Afficher", "Indécis", "Si vous souhaitez effacer ce type d'arbre :","Impossible d'ajouter une personne sans relation, sélectionnez d'abord quelqu'un !","Impossible de supprimer une personne avec des sous-branches ou un ID:0","Entrez d'abord le nom d'un arbre"],

["Espanol","Nombre del árbol:","Nombres:","Apellido:","Género:","Nacimiento:","Muerte:","Otra información:","Relación:","Botones:", "Hombre","Mujer","Ambos","Ninguno","Elegir","Casado > ","Paterno > ","Hermanos > ","Adoptado > ","Divorciado > ","Soltero > ", "Color de fondo", "Seleccionar varios", "Traducir:", "Líneas de identificación: seleccione el par de identificación y establezca la relación a la izquierda.", "Negro", "Blanco", "Rojo", "Verde", "Azul", "Naranja","Amarillo","Gris","La relación entre "," y ",". Puede cambiar esto usando el menú desplegable de relaciones a la izquierda.","Nueva persona","Actualizar seleccionado", "Eliminar seleccionados", "Pantalla completa", "Normal", "Nuevo árbol", "Guardar árbol", "Cargar árbol", "Centrar árbol", "Ocultar", "Mostrar", "indeciso", "Si desea borre este tipo de árbol:","No se puede agregar una persona sin relación, ¡seleccione a alguien primero!","No se puede eliminar una persona con subramas o ID:0","Ingrese primero un nombre de árbol"]

];
